### ISSUE TITLE
Update site for 2.0

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico.github.io#12]
- [x] Remove "cloud images" (to be replaced with docker images eventually)
- [x] Update references to 1.2 being the latest version - get latest version via AJAX [from pypi][1]?
- [x] Remove `easy_install` reference - only point to the install guide
- [x] Remove mention of python eggs. We only provide python wheels now, and they are on PyPI, not on GitHub
- [x] Update screenshots. Many are still from 1.2 or older 1.9.x versions

[1]: https://pypi.python.org/pypi/indico/json

**Comment by pferreir** [comment]
Already targeted by @meluru's new site version.
